[package]
name = "serde_rusqlite"
version = "0.37.0"
edition = "2021"
description = "Serialize/deserialize rusqlite rows"
keywords = ["serde", "sqlite", "rusqlite", "serialization", "deserialization"]
categories = ["database", "encoding"]
authors = ["Pro <twisted.fall@gmail.com>"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/serde_rusqlite"
repository = "https://github.com/twistedfall/serde_rusqlite"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rusqlite = "0.34"
serde = "1"

[dev-dependencies]
serde_bytes = "0.11"
serde_derive = "1"
